### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by bryanlandia** [appsembler/appsembleredx#5]
This was originally meant to be a repo holding various Appsembler specific Django apps, but it's better to make this specific to certificates setup.  Also, consider making this private if this is meant to be "secret sauce" /  used in Tahoe.   We will still be contributing some fixes to certs upstream.  @natea @abeals ?

**Comment by bryanlandia** [comment]
Will require updating a bunch of sites, unfortunately.  For a name, maybe `edx-certificates-setup`.

**Comment by abeals** [comment]
@bryanlandia I support this change you're proposing.
